pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building the application...'
                // Add build commands here
            }
        }

        stage('Test') {
            steps {
                echo 'Running tests...'
                sh 'pytest jenkins-pipeline-project/tests/test_app.py'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying the application...'
                sh 'jenkins-pipeline-project/pipelines/scripts/deploy.sh'
            }
        }
    }
}